import { useContext, useState, useEffect } from "react";
import { GlobalContext } from "@utils/GlobalContext";
import Router from "next/router";
import Head from 'next/head';
import Input from '@components/Input';
import Button from '@components/Button';
import nookies from 'nookies';
import { parseCookies } from 'nookies';
import Link from "next/link";
import { supabase } from "@libs/Supabase";

export async function getServerSideProps(context) {
  // Parse
  const cookies = nookies.get(context)

  if (!cookies.username) {
    return {
      redirect: {
        destination: "/login"
      }
    }
  }

  return {
    props: {
    }
  }
}

export default function AddArtist() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);
  const [input, setInput] = useState({ name: "", genre: "", image: "" });
  const [error, setError] = useState({ name: false, genre: false, image: false });
  const [success, setSuccess] = useState();
  const cookies = parseCookies();
  const isLoggedIn = cookies.username ? true : false;

  function handleChange(e) {
    setInput({
      ...input,
      [e.target.name]: e.target.value
    })
  }

  async function handleSubmit(e) {
    e.preventDefault();
    let inputError = false;
    if (!input.name) {
      setError({ ...error, name: true });
      inputError = true;
    }
    if (!input.genre) {
      setError({ ...error, genre: true });
      inputError = true;
    }
    if (!input.image) {
      setError({ ...error, image: true });
      inputError = true;
    }
    if (!inputError) {
      console.log("ready to insert")
      const { data, error } = await supabase
        .from('artist')
        .insert([
          {
            name: input.name,
            genre: input.genre,
            coverUrl: input.image
          }
        ])
      console.log(data);
      console.log(error);
      if (!error) {
        Router.push("/artists");
      }
    }
  }

  return (
    <>
      <Head>
        <title>Add Artist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen p-8 md:p-12">

        <div className="max-w-lg mx-auto">

          <nav className="flex justify-between mb-8 gap-x-4">
            <Link href="/">
              <a className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Songs</a>
            </Link>
            <Link href="/artists">
              <a className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Artists</a>
            </Link>
            {isLoggedIn &&
              <Link href="/logout">
                <a className="bg-red-500 px-2.5 py-0.5 text-white rounded hover:bg-red-600 text-sm  font-medium transition-all hover:cursor-pointer">Logout</a>
              </Link>
            }
            <div onClick={() => setDarkMode(!darkMode)} className="transition-all cursor-pointer w-12 h-7 dark:bg-blue-500 bg-neutral-200 rounded-full relative">
              <div className="h-5 w-5 bg-white rounded-full absolute top-1 transition-all dark:left-6 left-1"></div>
            </div>
          </nav>

          <section className="text-gray-600 body-font py-8 max-w-sm mx-auto">
            <h1 className="text-center font-medium text-3xl dark:text-whitem dark:text-white mb-4">Add Artist</h1>

            <Input onChange={handleChange} label="Name" name="name" placeholder="Name" type="text" />
            {error.name && <p className="text-red-500 text-center mb-2 text-xs font-medium">Name must not empty</p>}

            <Input onChange={handleChange} label="Genre" name="genre" placeholder="Pop / Rock" type="text" />
            {error.genre && <p className="text-red-500 text-center mb-2 text-xs font-medium">Genre must not empty</p>}

            <Input onChange={handleChange} label="Image URL From Spotify (https://i.scdn.co/image/...)" name="image" placeholder="https://i.scdn.co/image/ab67616d00001e02076747ead143aa3cd8c1d2f0" type="text" />
            {error.image && <p className="text-red-500 text-center mb-2 text-xs font-medium">Image URL must not empty</p>}

            <Button onClick={handleSubmit} className="w-full mt-4">Save Artist</Button>
            {success && <p className="text-green-500 text-center mt-4 text-xs font-medium">{success}</p>}
          </section>

        </div>

      </main>

    </>
  )
}