import { useContext, useState } from "react";
import { GlobalContext } from "@utils/GlobalContext";
import Router from "next/router";
import Head from 'next/head'
import axios from 'axios';
import Input from '@components/Input';
import Button from '@components/Button';
import nookies from 'nookies';
import InputPassword from "@components/InputPassword";
import Link from "next/link";

export default function Login() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);
  const [input, setInput] = useState(
    { username: "", password: "" }
  )
  const [error, setError] = useState()
  const [success, setSuccess] = useState()

  function handleChange(e) {
    setInput({
      ...input,
      [e.target.name]: e.target.value
    })
  }

  async function handleSubmit(e) {
    e.preventDefault();
    try {
      const { data } = await axios.post('/api/login', input);
      if (data.status === 200) {
        setSuccess("Success Login")
        setError("")
        nookies.set(null, 'username', input.username, {})
        Router.replace("/");
      } else {
        setSuccess("")
        setError(data.error)
      }
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen p-8 md:p-12">
        
        <div className="max-w-lg mx-auto">

          <nav className="flex justify-between mb-8 gap-x-4">
            <Link href="/">
              <span className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Songs</span>
            </Link>
            <Link href="/artists">
              <span className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Artists</span>
            </Link>
            <div onClick={() => setDarkMode(!darkMode)} className="transition-all cursor-pointer w-12 h-7 dark:bg-blue-500 bg-neutral-200 rounded-full relative">
              <div className="h-5 w-5 bg-white rounded-full absolute top-1 transition-all dark:left-6 left-1"></div>
            </div>
          </nav>

          <section className="text-gray-600 body-font py-8 max-w-sm mx-auto">
            <h1 className="text-center font-medium text-3xl dark:text-whitem dark:text-white mb-4">Login</h1>
            <Input onChange={handleChange} label="Username" name="username" placeholder="Username" type="text" />
            <InputPassword onChange={handleChange} label="Password" name="password" placeholder="Password" />
            <Button onClick={handleSubmit} className="w-full">Login</Button>
            {error && <p className="text-red-500 text-center mt-4 text-sm font-medium">{error}</p>}
            {success && <p className="text-green-500 text-center mt-4 text-sm font-medium">{success}</p>}
          </section>

        </div>

      </main>

    </>
  )
}

export async function getServerSideProps(context) {
  // Parse
  const cookies = nookies.get(context)

  if (cookies.username) {
    return {
      redirect: {
        destination: "/"
      }
    }
  }

  return {
    props: {
    }
  }
}